### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by azinsharaf** [makovich/kp#1]
Hi, Is there any plan to add Windows support for this repo?

Thanks, Azin

**Comment by makovich** [comment]
Have a good day, Azin!

There have to be two things addressed to make it possible. `skim` for now have no [Windows support](https://github.com/lotabout/skim/issues/293) and `kp` as you can see in its core uses this library heavily. Another one is an API that Windows provide to manage secrets internally (like [keyring](https://man7.org/linux/man-pages/man7/keyrings.7.html) in Linux or [Keychain](https://developer.apple.com/documentation/security/keychain_services) in macOS). Last time I looked at Windows, there were no common API. It was too much ago and things may have been changed.

However, since there is [WLS](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), it should work probably, but I don't have any chance to test it out. Key[ring|chain] only needed if you do not want to enter your password multiple times and so delegate auth to your OS.

If you looking for a way of using `kp` as a tool in your automation `*.bat`/`*.ps` scripts than it would be really good to add some kind of Windows support. Do you know any consistent APIs for secrets handling there on Windows?

**Comment by azinsharaf** [comment]
Thanks @makovich. I test it in WSL in the near future.

**Comment by azinsharaf** [comment]
@makovich  i am using it on WSL now. I may ask my questions in separate Issues.
